# Generated by Django 4.2.7 on 2023-11-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoggedIn',
            fields=[
                ('logged_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_panel.admin')),
                ('logged_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
