# Generated by Django 4.2.7 on 2023-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
